let bankSynonims = {
    "Allianz banque": ["allianz",],
    "Axa banque": ["aza",],
    "Banque BCP": ["bcp",],
    "Banque CIC Est": ["cic est","cic",],
    "Banque CIC Nord Ouest": ["cic nord est","cic",],
    "Banque CIC Ouest": ["cic ouest","cic",],
    "Banque CIC Sud Ouest": ["cic sud ouest","cic sud","cic",],
    "Banque Courtois - CN": ["banque courtois","courtois",],
    "Banque de Savoie BPCE": ["banque de savoie","banque savoie","savoie",],
    "BTP Banque": ["banque btp","btp","pro btp",],
    "Banque Européenne du Crédit Mutuel": ["becm","banque europenne","banque européenne",],
    "Banque Kolb CN": ["kolb",],
    "Banque Laydernier CN": ["laydernier",],
    "Banque Marze BPCE": ["marze bpce","marze",],
    "Banque Nuger CN": ["nuger",],
    "Banque Palatine": ["palatine",],
    "Banque Populaire Alsace Lorraine Champagne": ["banque pop","banque populaire","banque populaire alsace","banque populaire lorraine","banque populaire champagne",],
    "Banque Populaire Aquitaine Centre Atlantique": ["banque pop","banque populaire","banque populaire aquitaine","banque populaire centre","banque populaire atlantique",],
    "Banque Populaire Auvergne Rhone-Alpes": ["banque pop","banque populaire","banque populaire auvergne","banque populaire rhone",],
    "Banque Populaire Bourgogne Franche-Comté": ["banque pop","banque populaire","banque populaire bourgogne","banque populaire franche comté",],
    "Banque Populaire Grand Ouest": ["banque pop","banque populaire","banque populaire ouest","banque populaire de l'ouest",],
    "Banque Populaire du Nord": ["banque pop","banque populaire","banque populaire nord",],
    "Banque Populaire du Sud": ["banque pop","banque populaire","banque populaire sud",],
    "Banque Populaire Mediterranee": ["banque pop","banque populaire","banque populaire méditerranée",],
    "Banque Populaire Occitane": ["banque pop","banque populaire",],
    "Banque Populaire Rives de Paris": ["banque pop","banque populaire","banque populaire paris",],
    "Banque Populaire Val de France": ["banque pop","banque populaire",],
    "Banque privée 1818": ["banque privee","1818",],
    "Banque Rhône-Alpes - CN": ["banque rhone alpes",],
    "Banque Tarneaud - CN": ["tarneaud",],
    "Barclays France": ["barclays",],
    "BforBank": [],
    "BNP Paribas": ["bnp",],
    "Boursorama": ["bourso",],
    "BPCE": [],
    "BPE": [],
    "BRED": [],
    "Caisse agricole Crédit Mutuel": [],
    "Caisse centrale du crédit immobilier de France-3CIF": ["cif","crédit immobilier de France","credit immo de France",],
    "Caisse de Bretagne de crédit mutuel agricole": ["credit mutuel","credit mut","crédit mutuel","crédit mut","crédit mutuel de bretagne",],
    "Caisse d'Epargne CEPAC": ["CEPAC","caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne Aquitaine Poitou-Charentes": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne Bretagne-Pays de Loire": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne Côte d'Azur": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne d'Alsace": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne d'Auvergne et du Limousin": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne de Bourgogne Franche-Comté": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne de Lorraine Champagne-Ardenne": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne de Midi-Pyrénées": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne de Picardie": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne de Rhône Alpes": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne du Languedoc Roussillon": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne Ile-de-France": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne Loire Drôme Ardèche": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne Loire-Centre": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne Nord France Europe": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse d'épargne Normandie": ["caisse d'epargne","caisse d'épargne","caisse d'ep",],
    "Caisse fédérale de crédit mutuel": [],
    "Caisse fédérale du crédit mutuel de Maine-Anjou et Basse-Normandie": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Caisse fédérale du crédit mutuel Nord Europe": ["credit mutuel","credit mut","crédit mutuel","crédit mut","cmne",],
    "Caisse fédérale du crédit mutuel Océan": ["credit mutuel","credit mut","crédit mutuel","crédit mut","ocean",],
    "Crédit Agricole Alsace Vosges": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de l'Anjou et du Maine": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Atlantique Vendée": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Brie Picardie": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Centre Loire": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Centre-Est": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Charente-Maritime Deux-Sèvres": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Charente-Périgord": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole d'Alpes-Provence": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole d'Aquitaine": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de Centre France": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de Champagne-Bourgogne": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de Franche-Comté": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de la Corse": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de la Touraine et du Poitou": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de Lorraine": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de Normandie": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole de Paris et d'Ile-de-France": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole des Côtes-d'Armor": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole des Savoie": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole d'Ille-et-Vilaine": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole du Centre Ouest": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole du Finistère": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole du Languedoc": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole du Morbihan": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole du Nord Est": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Loire - Haute-Loire": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Nord de France": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Nord Midi-Pyrénées": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Normandie-Seine": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Provence-Côte d'Azur": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Pyrénées-Gascogne": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Sud Rhône-Alpes": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Sud-Méditerranée (Ariège et Pyrénées-Orientales)": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Toulouse": ["ca","credit agricole","crédit agricole",],
    "Crédit Agricole Val de France": ["ca","credit agricole","crédit agricole",],
    "Crédit Maritime Méditerranée": ["credit maritime","crédit maritime","mediterranee",],
    "Caisse régionale de crédit maritime mutuel du littoral du sud ouest": ["credit maritime","crédit maritime","sud ouest",],
    "CASDEN Banque Populaire": ["casden",],
    "CIC Banque Transatlantique": ["cic","transatlantique","banque transatlantique",],
    "CIC Iberbanco": ["cic","iberbanco",],
    "Crédit Coopératif": ["credit cooperatif",],
    "Crédit du Nord": ["credit du nord","credit nord",],
    "Crédit Foncier de France": ["cff","credit foncier de France","credit foncier France",],
    "Crédit foncier et communal d'Alsace et de Lorraine-Banque": ["cfc","credit foncier et communal",],
    "CIC": ["cic",],
    "LCL": ["credit lyonnais","crédit lyonnais","cl",],
    "CIF Patrimoine & Immobilier": ["cif",],
    "HSBC France": ["hsbc",],
    "La Banque Postale": ["banque postale","poste",],
    "Lyonnaise de banque CIC": ["lyonnaise","lyonnaise de banque",],
    "Société Générale": ["societe generale","socgen","soc gen","soge","sogé", "sg"],
    "Société marseillaise de crédit CN": ["societe marseillaise de credit","societe marseillaise",],
    "Credit Mutuel Anjou": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel de Bretagne": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Crédit Mutuel Sud Ouest": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel du Massif Central": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Centre": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Centre Est Europe": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Dauphiné Vivarais": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Ile de France": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Loire Atlantique, Centre Est": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Mediterranée": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Normandie": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Nord Europe": ["credit mutuel","credit mut","crédit mutuel","crédit mut","cmne",],
    "Crédit Mutuel Midi Atlantique": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Savoie-Mont Blanc": ["credit mutuel","credit mut","crédit mutuel","crédit mut",],
    "Credit Mutuel Sud Est": ["credit mutuel","credit mut","crédit mutuel","crédit mut",]
}

module.exports = {
    bankSynonims
}